### ISSUE TITLE
Are network features normalized?

### ISSUE THREAD

**Issue by kiaraasmith** [krishnanlab/GenePlexus#2]
This is a great analysis! I just wanted to check if the different networks are normalized when used for LP, SL methods (same with the embeddings constructed using node2vec).

**Comment by RemyLau** [comment]
Hi sorry for the delayed response, the features are not normalized as being set up in this repo. We've tried to normalize (e.g. standardize the columns), but that turned out to hurt the performance quite a bit.

**Comment by RemyLau** [comment]
I'll close this issue here, feel free to contact me via email: liurenmi@msu.edu if you have any further questions!
